version: "3"

services:
    postgres:
        container_name: "kachnaonline-postgres"
        hostname: "postgres"
        image: "docker.io/postgres:16"
        restart: unless-stopped
        expose:
            - "5432"
        ports:
            # Avoid clashes with localhost postgres
            - "6543:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        env_file:
            - docker/database.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kachna"]
            interval: 5s
            timeout: 5s
            retries: 5
    api:
        build:
            context: ./KachnaOnline.App
            dockerfile: Dockerfile.development
            args:
                UID: "${UID:-1000}"
                GID: "${GID:-1000}"
        restart: unless-stopped
        volumes:
            - ./:/src:z
        env_file:
            - docker/api.env
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -k https://localhost:5001/kachna/api/states/current"]
            interval: 5s
            timeout: 5s
            retries: 5
        command: "${DOTNET_ARGS:-}"
    frontend:
        build:
            dockerfile: Dockerfile.development
            context: ./ClientApp/KachnaOnline
        restart: unless-stopped
        volumes:
            - ./ClientApp/KachnaOnline/:/src:z
        ports:
            - "4200:4200"
        depends_on:
            api:
                condition: service_healthy

volumes:
    database-data:

networks:
    default:
        driver_opts:
            isolate: "true"
