name: Docker Image CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    PublishImage:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push the Kachna Online backend
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./KachnaOnline.App/Dockerfile
                  push: true
                  tags: ghcr.io/su-fit-vut/kachna-online-backend:latest
